FROM registry.cn-hangzhou.aliyuncs.com/mszlu/go:1.19 AS build-stage
WORKDIR /app
COPY . ./
RUN go env -w GO111MODULE=on
RUN go env -w GOPROXY=https://goproxy.cn,direct
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build  -o /app/exchangeApi exchange-api/main.go
FROM registry.cn-hangzhou.aliyuncs.com/mszlu-gcrio/distroless_base-debian11 AS build-release-stage
WORKDIR /
COPY --from=build-stage /app/exchangeApi /exchange-api
COPY --from=build-stage /app/exchange-api/etc/conf-prod.yaml /etc/conf.yaml
EXPOSE 8890
USER nonroot:nonroot
ENTRYPOINT ["/exchange-api"]