// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: playground.proto

package server

import (
	"context"

	"solana/internal/logic"
	"solana/internal/svc"
	"grpc-common/solana/types/playground"
)

type PlaygroundServer struct {
	svcCtx *svc.ServiceContext
	playground.UnimplementedPlaygroundServer
}

func NewPlaygroundServer(svcCtx *svc.ServiceContext) *PlaygroundServer {
	return &PlaygroundServer{
		svcCtx: svcCtx,
	}
}

func (s *PlaygroundServer) GetBalance(ctx context.Context, in *playground.GetBalanceRequest) (*playground.GetBalanceResponse, error) {
	l := logic.NewGetBalanceLogic(ctx, s.svcCtx)
	return l.GetBalance(in)
}

func (s *PlaygroundServer) Transfer(ctx context.Context, in *playground.TransferRequest) (*playground.TransferResponse, error) {
	l := logic.NewTransferLogic(ctx, s.svcCtx)
	return l.Transfer(in)
}

func (s *PlaygroundServer) Airdrop(ctx context.Context, in *playground.AirdropRequest) (*playground.AirdropResponse, error) {
	l := logic.NewAirdropLogic(ctx, s.svcCtx)
	return l.Airdrop(in)
}
