// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: playground.proto

package playground

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_playground_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playground_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_playground_proto_rawDescGZIP(), []int{0}
}

func (x *GetBalanceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       float64                `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_playground_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_playground_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_playground_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetBalanceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAddress   string                 `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress     string                 `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,4,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_playground_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playground_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_playground_proto_rawDescGZIP(), []int{2}
}

func (x *TransferRequest) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *TransferRequest) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *TransferRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferRequest) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_playground_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_playground_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_playground_proto_rawDescGZIP(), []int{3}
}

func (x *TransferResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *TransferResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AirdropRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AirdropRequest) Reset() {
	*x = AirdropRequest{}
	mi := &file_playground_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AirdropRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirdropRequest) ProtoMessage() {}

func (x *AirdropRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playground_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirdropRequest.ProtoReflect.Descriptor instead.
func (*AirdropRequest) Descriptor() ([]byte, []int) {
	return file_playground_proto_rawDescGZIP(), []int{4}
}

func (x *AirdropRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AirdropRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AirdropResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AirdropResponse) Reset() {
	*x = AirdropResponse{}
	mi := &file_playground_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AirdropResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirdropResponse) ProtoMessage() {}

func (x *AirdropResponse) ProtoReflect() protoreflect.Message {
	mi := &file_playground_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirdropResponse.ProtoReflect.Descriptor instead.
func (*AirdropResponse) Descriptor() ([]byte, []int) {
	return file_playground_proto_rawDescGZIP(), []int{5}
}

func (x *AirdropResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *AirdropResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_playground_proto protoreflect.FileDescriptor

const file_playground_proto_rawDesc = "" +
	"\n" +
	"\x10playground.proto\x12\n" +
	"playground\"-\n" +
	"\x11GetBalanceRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"D\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x01R\abalance\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x8c\x01\n" +
	"\x0fTransferRequest\x12!\n" +
	"\ffrom_address\x18\x01 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x02 \x01(\tR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1f\n" +
	"\vprivate_key\x18\x04 \x01(\tR\n" +
	"privateKey\"F\n" +
	"\x10TransferResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"B\n" +
	"\x0eAirdropRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"E\n" +
	"\x0fAirdropResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xe4\x01\n" +
	"\n" +
	"Playground\x12K\n" +
	"\n" +
	"GetBalance\x12\x1d.playground.GetBalanceRequest\x1a\x1e.playground.GetBalanceResponse\x12E\n" +
	"\bTransfer\x12\x1b.playground.TransferRequest\x1a\x1c.playground.TransferResponse\x12B\n" +
	"\aAirdrop\x12\x1a.playground.AirdropRequest\x1a\x1b.playground.AirdropResponseB\x0eZ\f./playgroundb\x06proto3"

var (
	file_playground_proto_rawDescOnce sync.Once
	file_playground_proto_rawDescData []byte
)

func file_playground_proto_rawDescGZIP() []byte {
	file_playground_proto_rawDescOnce.Do(func() {
		file_playground_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_playground_proto_rawDesc), len(file_playground_proto_rawDesc)))
	})
	return file_playground_proto_rawDescData
}

var file_playground_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_playground_proto_goTypes = []any{
	(*GetBalanceRequest)(nil),  // 0: playground.GetBalanceRequest
	(*GetBalanceResponse)(nil), // 1: playground.GetBalanceResponse
	(*TransferRequest)(nil),    // 2: playground.TransferRequest
	(*TransferResponse)(nil),   // 3: playground.TransferResponse
	(*AirdropRequest)(nil),     // 4: playground.AirdropRequest
	(*AirdropResponse)(nil),    // 5: playground.AirdropResponse
}
var file_playground_proto_depIdxs = []int32{
	0, // 0: playground.Playground.GetBalance:input_type -> playground.GetBalanceRequest
	2, // 1: playground.Playground.Transfer:input_type -> playground.TransferRequest
	4, // 2: playground.Playground.Airdrop:input_type -> playground.AirdropRequest
	1, // 3: playground.Playground.GetBalance:output_type -> playground.GetBalanceResponse
	3, // 4: playground.Playground.Transfer:output_type -> playground.TransferResponse
	5, // 5: playground.Playground.Airdrop:output_type -> playground.AirdropResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_playground_proto_init() }
func file_playground_proto_init() {
	if File_playground_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_playground_proto_rawDesc), len(file_playground_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_playground_proto_goTypes,
		DependencyIndexes: file_playground_proto_depIdxs,
		MessageInfos:      file_playground_proto_msgTypes,
	}.Build()
	File_playground_proto = out.File
	file_playground_proto_goTypes = nil
	file_playground_proto_depIdxs = nil
}
